version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=training
    ports:
      - 3307:3306

  app:
    image: srinjoy0810/docker-repo:spring
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/training
    depends_on:
      - docker-mysql

networks:
  example: